name: Gatsby Build and Deploy to GitHub Pages
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: |
        git config --global user.email "williams.e.christian@gmail.com"
        git config --global user.name "cwmoon"
    - run: yarn deploy:prod
      env:
        CI: true
        PA_TOKEN: ${{ secrets.PA_TOKEN }}